import type { Metadata } from "next";
import React from "react";
import { Inter } from "next/font/google";

import "./globals.css";
import Header from "./(components)/Header/Header";

const inter = Inter({ subsets: ["latin"], weight: "300" });

export const metadata: Metadata = {
  title: "Mega Dev",
  description: "Generated by create next app",
  icons: {
    icon: "/svg/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div id="blur_layer" />
        <div id="container">
          <Header />
          {children}
        </div>
      </body>
    </html>
  );
}
