

name: Docker Image CI

run-name: ${{ github.actor }} Docker Images build 🚀

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build --platform linux/arm64/v8 -t kimsunin/blog-fe .
